### ISSUE TITLE
Pipenv lock fails on linux

### ISSUE THREAD

**Issue by simonft** [firstlookmedia/flock-agent#51]
Pipenv needs to be able to run the setup.py of a package to resolve the dependencies and lock it to a version. Right now it can't do that for pyobjc-* packages on linux. 

https://github.com/pypa/pipenv/issues/3187

**Comment by micahflee** [comment]
Maybe it's worth changing this, but at the moment I'm installing all Linux dependencies through package managers, and only using pipenv for the macOS version. See https://github.com/firstlookmedia/flock-agent/blob/master/BUILD.md#linux

This way it's much simpler for Linux distros to choose to package flock-agent in the future. However, there isn't really a plan for how to distribute Linux packages yet, so maybe it would make sense to use pipenv for Linux too.

**Comment by simonft** [comment]
Hmmm. I was trying to use pipenv to add and install a dev dependencies. But the stuff I actually need seems to already be packaged so maybe it's not a big deal. I guess I just have to ask someone with OSX to run pipenv lock when I need to add a dependency. 

This seems like a weird thing that might become a hurdle/confusion to others trying to contribute in the future but maybe the pipenv/pyobjc issue will be fixed at some point.

**Comment by micahflee** [comment]
This is a good point. It turns out, it's easy to make pipenv cross-platform, so I just made a PR that does it.
